import { Timestamp } from 'firebase/firestore';

// ── Payment type ──────────────────────────────────────────────
export type SalePaymentType = 'cash' | 'credit' | 'partial';
export type PaymentMethod   = 'cash' | 'benefit' | 'bank_transfer' | 'cheque' | 'other';

// ── Line item ─────────────────────────────────────────────────
export interface SaleLineItem {
  productId:   string;
  productName: string;
  productCode: string;
  unit:        string;
  qty:         number;
  unitPrice:   number;
  discount:    number;   // per-line discount amount (not %)
  lineTotal:   number;   // (qty * unitPrice) - discount
}

// ── Sale document ─────────────────────────────────────────────
// Created by UI. Stock + balance updated by Cloud Function.
export interface Sale {
  id:              string;
  companyId:       string;
  invoiceNumber:   string;      // generated by CF, e.g. INV-2026-0001
  customerId:      string;
  customerName:    string;
  date:            Timestamp;
  invoiceDate:     Timestamp;        // always = sale date for MVP
  dueDate:         Timestamp | null; // nullable — for future credit terms
  creditDays:      number | null;    // nullable — e.g. 30, 60, 90
  items:           SaleLineItem[];
  subtotal:        number;      // sum of (qty * unitPrice)
  discountTotal:   number;      // sum of all line discounts
  grandTotal:      number;      // subtotal - discountTotal
  paymentType:     SalePaymentType;
  amountReceived:  number;      // for partial: amount paid now; cash: = grandTotal; credit: 0
  amountDue:       number;      // grandTotal - amountReceived
  paymentMethod:   PaymentMethod | null;  // for cash/partial
  notes:           string | null;
  isVoid:          boolean;
  voidReason:      string | null;
  voidedAt:        Timestamp | null;
  voidedBy:        string | null;
  // CF-managed fields — never written by client after creation
  receiptId:       string | null;   // auto-created receipt for cash/partial
  stockProcessed:  boolean;         // CF marks true after stock decremented
  balanceProcessed:boolean;         // CF marks true after customer balance updated
  voidProcessed:   boolean;         // CF marks true after void reversal complete
  status:          'pending' | 'confirmed' | 'voided' | 'failed';
  failureReason:   string | null;   // set by CF if processing fails
  createdAt:       Timestamp;
  updatedAt:       Timestamp;
  createdBy:       string;
}

// ── New sale form state ───────────────────────────────────────
export interface NewSaleForm {
  customerId:     string;
  customerName:   string;
  date:           string;
  items:          NewSaleLineItem[];
  paymentType:    SalePaymentType;
  amountReceived: string;
  paymentMethod:  PaymentMethod;
  notes:          string;
}

export interface NewSaleLineItem {
  productId:   string;
  productName: string;
  productCode: string;
  unit:        string;
  stock:       number;    // current stock — for availability check
  qty:         string;
  unitPrice:   string;
  discount:    string;
}

// ── Sample data ───────────────────────────────────────────────
export const sampleSales: Sale[] = [
  {
    id: 'sale1', companyId: 'demo',
    invoiceNumber: 'INV-2026-0001',
    customerId: 'c1', customerName: 'Gulf Foods Co.',
    date: Timestamp.fromDate(new Date('2026-05-10')),
    invoiceDate: Timestamp.fromDate(new Date('2026-05-10')),
    dueDate: null,
    creditDays: null,
    items: [
      { productId: 'p1', productName: 'Rice 25kg Bag', productCode: 'PRD-001',
        unit: 'BAG', qty: 5, unitPrice: 22.000, discount: 0, lineTotal: 110.000 },
      { productId: 'p5', productName: 'Vegetable Oil 1L', productCode: 'PRD-005',
        unit: 'CTN', qty: 8, unitPrice: 10.500, discount: 4.000, lineTotal: 80.000 },
    ],
    subtotal: 194.000, discountTotal: 4.000, grandTotal: 190.000,
    paymentType: 'credit', amountReceived: 0, amountDue: 190.000,
    paymentMethod: null, notes: null,
    isVoid: false, voidReason: null, voidedAt: null, voidedBy: null,
    receiptId: null, stockProcessed: true, balanceProcessed: true,
    voidProcessed: false, failureReason: null, status: 'confirmed',
    createdAt: Timestamp.fromDate(new Date('2026-05-10')),
    updatedAt: Timestamp.fromDate(new Date('2026-05-10')),
    createdBy: 'owner',
  },
  {
    id: 'sale2', companyId: 'demo',
    invoiceNumber: 'INV-2026-0002',
    customerId: 'c2', customerName: 'XYZ Store',
    date: Timestamp.fromDate(new Date('2026-05-18')),
    invoiceDate: Timestamp.fromDate(new Date('2026-05-18')),
    dueDate: null,
    creditDays: null,
    items: [
      { productId: 'p6', productName: 'Mineral Water 1.5L', productCode: 'PRD-006',
        unit: 'CTN', qty: 10, unitPrice: 3.500, discount: 0, lineTotal: 35.000 },
    ],
    subtotal: 35.000, discountTotal: 0, grandTotal: 35.000,
    paymentType: 'cash', amountReceived: 35.000, amountDue: 0,
    paymentMethod: 'cash', notes: null,
    isVoid: false, voidReason: null, voidedAt: null, voidedBy: null,
    receiptId: 'rct1', stockProcessed: true, balanceProcessed: true,
    voidProcessed: false, failureReason: null, status: 'confirmed',
    createdAt: Timestamp.fromDate(new Date('2026-05-18')),
    updatedAt: Timestamp.fromDate(new Date('2026-05-18')),
    createdBy: 'owner',
  },
  {
    id: 'sale3', companyId: 'demo',
    invoiceNumber: 'INV-2026-0003',
    customerId: 'c3', customerName: 'City Mart',
    date: Timestamp.fromDate(new Date('2026-06-01')),
    invoiceDate: Timestamp.fromDate(new Date('2026-06-01')),
    dueDate: null,
    creditDays: null,
    items: [
      { productId: 'p4', productName: 'Canned Tomatoes 400g', productCode: 'PRD-004',
        unit: 'CTN', qty: 20, unitPrice: 6.000, discount: 10.000, lineTotal: 110.000 },
    ],
    subtotal: 120.000, discountTotal: 10.000, grandTotal: 110.000,
    paymentType: 'partial', amountReceived: 50.000, amountDue: 60.000,
    paymentMethod: 'bank_transfer', notes: 'Remaining due end of month',
    isVoid: false, voidReason: null, voidedAt: null, voidedBy: null,
    receiptId: 'rct2', stockProcessed: true, balanceProcessed: true,
    voidProcessed: false, failureReason: null, status: 'confirmed',
    createdAt: Timestamp.fromDate(new Date('2026-06-01')),
    updatedAt: Timestamp.fromDate(new Date('2026-06-01')),
    createdBy: 'owner',
  },
];
